# Data Generator for A9A Assessment

This notebook generates the required CSV files as described in the dataset instructions. Each file will be saved in the `../data/` folder. Unknown columns are filled with relevant names, and `Mission_Title` is included in all files to link them together.

## Instructions

This notebook generates the following CSV files in the `../data/` folder:

1. Cyber_Document_Library
2. Equipment_Issues
3. FFIRs_Friction_Points_Recommendations
4. Hardening_Recommendations
5. Mission_Details
6. Mission_Metrics
7. Missions_by_Location_and_Tasked_System
8. Tactical_Lessons_Learned

Each file includes a `Mission_Title` column to link records across files. Unknown columns are filled with relevant names. Long text columns are simulated with sample text.

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import os

# Output directory
DATA_DIR = '../data/'
os.makedirs(DATA_DIR, exist_ok=True)

# Helper function to generate random mission titles
def generate_mission_titles(n):
    return [f"Mission_{i+1}" for i in range(n)]

# Helper function for random text
def random_text(length=50):
    return ' '.join(np.random.choice(['cyber', 'threat', 'intel', 'operation', 'system', 'network', 'security', 'assessment', 'response', 'incident'], size=length))

In [2]:
# 1) Cyber_Document_Library
n_rows = 10
mission_titles = generate_mission_titles(n_rows)
cyber_doc_columns = ['Mission_Title', 'Doc_ID', 'Doc_Type', 'Doc_Date', 'Classification', 'Author', 'Review_Status']
cyber_doc_df = pd.DataFrame({
    'Mission_Title': mission_titles,
    'Doc_ID': [f'DOC{i+1:03d}' for i in range(n_rows)],
    'Doc_Type': np.random.choice(['Report', 'Memo', 'Briefing'], n_rows),
    'Doc_Date': pd.date_range(datetime.today(), periods=n_rows).strftime('%Y-%m-%d'),
    'Classification': np.random.choice(['Unclassified', 'Secret', 'Top Secret'], n_rows),
    'Author': np.random.choice(['Analyst A', 'Analyst B', 'Analyst C'], n_rows),
    'Review_Status': np.random.choice(['Pending', 'Reviewed', 'Rejected'], n_rows)
})
cyber_doc_df.to_csv(os.path.join(DATA_DIR, 'Cyber_Document_Library.csv'), index=False)
cyber_doc_df.head()

,Mission_Title,Doc_ID,Doc_Type,Doc_Date,Classification,Author,Review_Status
0,Mission_1,DOC001,Memo,2025-12-04,Top Secret,Analyst B,Reviewed
1,Mission_2,DOC002,Memo,2025-12-05,Secret,Analyst A,Reviewed
2,Mission_3,DOC003,Report,2025-12-06,Secret,Analyst B,Reviewed
3,Mission_4,DOC004,Briefing,2025-12-07,Secret,Analyst A,Pending
4,Mission_5,DOC005,Memo,2025-12-08,Secret,Analyst B,Rejected

In [3]:
# 2) Equipment_Issues
n_rows = 10
equipment_issues_columns = ['Mission_Title', 'Issue_ID', 'Equipment_Type', 'Reported_By', 'Date_Reported', 'Status', 'Equipment Issues']
equipment_issues_df = pd.DataFrame({
    'Mission_Title': mission_titles,
    'Issue_ID': [f'ISSUE{i+1:03d}' for i in range(n_rows)],
    'Equipment_Type': np.random.choice(['Laptop', 'Router', 'Server', 'Switch'], n_rows),
    'Reported_By': np.random.choice(['User A', 'User B', 'User C'], n_rows),
    'Date_Reported': pd.date_range(datetime.today(), periods=n_rows).strftime('%Y-%m-%d'),
    'Status': np.random.choice(['Open', 'Closed', 'In Progress'], n_rows),
    'Equipment Issues': [random_text(100) for _ in range(n_rows)]
})
equipment_issues_df.to_csv(os.path.join(DATA_DIR, 'Equipment_Issues.csv'), index=False)
equipment_issues_df.head()

,Mission_Title,Issue_ID,Equipment_Type,Reported_By,Date_Reported,Status,Equipment Issues
0,Mission_1,ISSUE001,Server,User B,2025-12-04,Closed,network operation cyber threat intel response ...
1,Mission_2,ISSUE002,Server,User C,2025-12-05,Open,intel system cyber response intel cyber incide...
2,Mission_3,ISSUE003,Router,User C,2025-12-06,Closed,system operation intel incident intel system s...
3,Mission_4,ISSUE004,Router,User A,2025-12-07,In Progress,incident system assessment intel security netw...
4,Mission_5,ISSUE005,Switch,User A,2025-12-08,In Progress,security response operation incident operation...

In [4]:
# 3) FFIRs, Friction Points, Recommendations
n_rows = 10
ffirs_columns = ['Mission_Title', 'FFIR', 'Friction_Point', 'Recommendation', 'Observation', 'Action_Item', 'Summary']
ffirs_df = pd.DataFrame({
    'Mission_Title': mission_titles,
    'FFIR': [random_text(80) for _ in range(n_rows)],
    'Friction_Point': [random_text(80) for _ in range(n_rows)],
    'Recommendation': [random_text(80) for _ in range(n_rows)],
    'Observation': [random_text(80) for _ in range(n_rows)],
    'Action_Item': [random_text(80) for _ in range(n_rows)],
    'Summary': [random_text(80) for _ in range(n_rows)]
})
ffirs_df.to_csv(os.path.join(DATA_DIR, 'FFIRs_Friction_Points_Recommendations.csv'), index=False)
ffirs_df.head()

,Mission_Title,FFIR,Friction_Point,Recommendation,Observation,Action_Item,Summary
0,Mission_1,operation intel system system intel assessment...,network intel network incident network threat ...,operation intel system intel cyber security re...,security intel security network cyber system i...,network intel cyber system system incident cyb...,incident security intel intel operation respon...
1,Mission_2,response threat system response threat inciden...,network response cyber response assessment res...,assessment cyber intel operation threat incide...,incident intel operation operation threat inci...,assessment assessment incident threat network ...,response assessment assessment threat network ...
2,Mission_3,system intel assessment system threat incident...,response cyber intel operation cyber incident ...,cyber response operation response assessment i...,intel security system network incident assessm...,security network system intel response respons...,cyber cyber response security incident cyber r...
3,Mission_4,operation security intel system intel assessme...,intel cyber threat threat threat cyber respons...,operation threat threat response cyber securit...,assessment assessment assessment response resp...,security intel response assessment assessment ...,operation incident incident incident assessmen...
4,Mission_5,network system assessment threat system intel ...,response response threat cyber system threat n...,threat operation intel security operation syst...,assessment network response assessment operati...,incident response security assessment assessme...,network operation system security intel system...

In [5]:
# 4) Hardening Recommendations
n_rows = 10
hardening_columns = ['Mission_Title', 'Recommendation_ID', 'System_Affected', 'Priority', 'Status', 'Hardening Recommendation #231']
hardening_df = pd.DataFrame({
    'Mission_Title': mission_titles,
    'Recommendation_ID': [f'HR{i+1:03d}' for i in range(n_rows)],
    'System_Affected': np.random.choice(['System A', 'System B', 'System C'], n_rows),
    'Priority': np.random.choice(['High', 'Medium', 'Low'], n_rows),
    'Status': np.random.choice(['Implemented', 'Pending', 'Rejected'], n_rows),
    'Hardening Recommendation #231': [random_text(120) for _ in range(n_rows)]
})
hardening_df.to_csv(os.path.join(DATA_DIR, 'Hardening_Recommendations.csv'), index=False)
hardening_df.head()

,Mission_Title,Recommendation_ID,System_Affected,Priority,Status,Hardening Recommendation #231
0,Mission_1,HR001,System A,Low,Pending,incident incident incident incident cyber resp...
1,Mission_2,HR002,System C,High,Rejected,intel incident security incident assessment op...
2,Mission_3,HR003,System A,High,Rejected,incident network response assessment security ...
3,Mission_4,HR004,System C,High,Rejected,response response system system assessment ope...
4,Mission_5,HR005,System A,Low,Pending,intel operation security assessment threat sec...

In [6]:
# 5) Mission Details
n_rows = 10
mission_details_columns = [
    'CY', 'Mission_Title', 'Terrain_System_Past_End_of_Life', 'Terrain_Air_Gapped', 'Intel_Driven_Hunt',
    'TMP_Signing_Delay', 'ATC_Signing_Delay', 'ROC_Drill_Completed', 'ROC_Drill_Date', 'OIV_Conducted',
    'OIV_Date', 'CTE_Utilized', 'CTE_Date', 'Range_Utilized', 'Equipment_Issues', 'Equipment_Shipping',
    'CED_Orders_Issues', 'CED_Orders_Issues_Details', 'Badge_Building_Issues', 'Account_Issues',
    'Account_Issue_Details', 'Equipment_Issues_Details'
]
mission_details_df = pd.DataFrame({
    'CY': np.random.choice(['2024', '2025'], n_rows),
    'Mission_Title': mission_titles,
    'Terrain_System_Past_End_of_Life': np.random.choice([True, False], n_rows),
    'Terrain_Air_Gapped': np.random.choice([True, False], n_rows),
    'Intel_Driven_Hunt': np.random.choice([True, False], n_rows),
    'TMP_Signing_Delay': np.random.choice([True, False], n_rows),
    'ATC_Signing_Delay': np.random.choice([True, False], n_rows),
    'ROC_Drill_Completed': np.random.choice([True, False], n_rows),
    'ROC_Drill_Date': pd.date_range(datetime.today(), periods=n_rows).strftime('%Y-%m-%d'),
    'OIV_Conducted': np.random.choice([True, False], n_rows),
    'OIV_Date': pd.date_range(datetime.today(), periods=n_rows).strftime('%Y-%m-%d'),
    'CTE_Utilized': np.random.choice([True, False], n_rows),
    'CTE_Date': pd.date_range(datetime.today(), periods=n_rows).strftime('%Y-%m-%d'),
    'Range_Utilized': np.random.choice([True, False], n_rows),
    'Equipment_Issues': np.random.choice([True, False], n_rows),
    'Equipment_Shipping': np.random.choice(['Shipped', 'Delayed', 'Lost'], n_rows),
    'CED_Orders_Issues': np.random.choice([True, False], n_rows),
    'CED_Orders_Issues_Details': np.random.choice(['None', 'Delay', 'Lost'], n_rows),
    'Badge_Building_Issues': np.random.choice(['None', 'Access Denied', 'Lost Badge'], n_rows),
    'Account_Issues': np.random.choice([True, False], n_rows),
    'Account_Issue_Details': np.random.choice(['None', 'Password Reset', 'Locked Out'], n_rows),
    'Equipment_Issues_Details': np.random.choice(['None', 'Damaged', 'Missing'], n_rows)
})
mission_details_df.to_csv(os.path.join(DATA_DIR, 'Mission_Details.csv'), index=False)
mission_details_df.head()

,CY,Mission_Title,Terrain_System_Past_End_of_Life,Terrain_Air_Gapped,Intel_Driven_Hunt,TMP_Signing_Delay,ATC_Signing_Delay,ROC_Drill_Completed,ROC_Drill_Date,OIV_Conducted,...,CTE_Date,Range_Utilized,Equipment_Issues,Equipment_Shipping,CED_Orders_Issues,CED_Orders_Issues_Details,Badge_Building_Issues,Account_Issues,Account_Issue_Details,Equipment_Issues_Details
0,2024,Mission_1,True,True,True,True,True,False,2025-12-04,False,...,2025-12-04,True,True,Lost,False,Lost,Lost Badge,True,Password Reset,Missing
1,2025,Mission_2,True,False,False,True,False,False,2025-12-05,True,...,2025-12-05,False,False,Delayed,True,Lost,Access Denied,True,Locked Out,Missing
2,2025,Mission_3,False,True,False,True,False,True,2025-12-06,True,...,2025-12-06,False,False,Delayed,True,Delay,Lost Badge,True,Password Reset,Missing
3,2024,Mission_4,False,True,True,False,False,True,2025-12-07,True,...,2025-12-07,True,True,Delayed,False,None,None,True,Locked Out,None
4,2024,Mission_5,True,True,False,False,True,True,2025-12-08,True,...,2025-12-08,True,True,Shipped,True,Delay,Access Denied,False,Password Reset,Damaged

In [7]:
# 6) Mission_Metrics
n_rows = 10
mission_metrics_columns = [
    'CY', 'Mission_Title', 'Number_of_JCO_Reports', 'Number_of_Tactical_Objectives', 'Number_of_Tactical_Tasks',
    'Number_of_Investigations', 'Number_of_Capability_Gaps', 'Number_of_Vulnerabilities',
    'Number_of_Hardening_Recommendations', 'Number_of_Terrain_TTPs', 'Number_of_ECOA_TTPs'
]
mission_metrics_df = pd.DataFrame({
    'CY': np.random.choice(['2024', '2025'], n_rows),
    'Mission_Title': mission_titles,
    'Number_of_JCO_Reports': np.random.randint(1, 10, n_rows),
    'Number_of_Tactical_Objectives': np.random.randint(1, 10, n_rows),
    'Number_of_Tactical_Tasks': np.random.randint(1, 10, n_rows),
    'Number_of_Investigations': np.random.randint(0, 5, n_rows),
    'Number_of_Capability_Gaps': np.random.randint(0, 5, n_rows),
    'Number_of_Vulnerabilities': np.random.randint(0, 5, n_rows),
    'Number_of_Hardening_Recommendations': np.random.randint(0, 5, n_rows),
    'Number_of_Terrain_TTPs': np.random.randint(0, 5, n_rows),
    'Number_of_ECOA_TTPs': np.random.randint(0, 5, n_rows)
})
mission_metrics_df.to_csv(os.path.join(DATA_DIR, 'Mission_Metrics.csv'), index=False)
mission_metrics_df.head()

,CY,Mission_Title,Number_of_JCO_Reports,Number_of_Tactical_Objectives,Number_of_Tactical_Tasks,Number_of_Investigations,Number_of_Capability_Gaps,Number_of_Vulnerabilities,Number_of_Hardening_Recommendations,Number_of_Terrain_TTPs,Number_of_ECOA_TTPs
0,2024,Mission_1,5,9,4,3,3,3,2,4,3
1,2025,Mission_2,7,7,9,0,2,1,3,0,4
2,2024,Mission_3,8,3,2,4,1,1,0,2,3
3,2025,Mission_4,9,4,3,3,3,4,0,0,2
4,2025,Mission_5,8,5,2,3,1,0,0,1,3

In [8]:
# 7) Missions by Location & Tasked System
n_rows = 10
missions_location_columns = [
    'CY', 'Mission_Title', 'Country', 'State', 'City', 'Base', 'Tasked_System', 'Network_Map', 'Attachments',
    'Tasked_Sub_System', 'Misc_System_Info_Equipment', 'CPT_Equipment', 'Tools', 'Terrain_Category',
    'Terrain_Network_Type', 'Terrain_Operating_System', 'Terrain_Enclave'
]
missions_location_df = pd.DataFrame({
    'CY': np.random.choice(['2024', '2025'], n_rows),
    'Mission_Title': mission_titles,
    'Country': np.random.choice(['USA', 'UK', 'Germany', 'Japan'], n_rows),
    'State': np.random.choice(['Ohio', 'Texas', 'Bavaria', 'Tokyo'], n_rows),
    'City': np.random.choice(['Dayton', 'San Antonio', 'Munich', 'Shinjuku'], n_rows),
    'Base': np.random.choice(['WPAFB', 'Randolph', 'Ramstein', 'Yokota'], n_rows),
    'Tasked_System': np.random.choice(['System X', 'System Y', 'System Z'], n_rows),
    'Network_Map': np.random.choice(['Map1', 'Map2', 'Map3'], n_rows),
    'Attachments': np.random.randint(0, 5, n_rows),
    'Tasked_Sub_System': np.random.choice(['SubA', 'SubB', 'SubC'], n_rows),
    'Misc_System_Info_Equipment': np.random.choice(['InfoA', 'InfoB', 'InfoC'], n_rows),
    'CPT_Equipment': np.random.choice(['EquipA', 'EquipB', 'EquipC'], n_rows),
    'Tools': np.random.choice(['ToolA', 'ToolB', 'ToolC'], n_rows),
    'Terrain_Category': np.random.choice(['CatA', 'CatB', 'CatC'], n_rows),
    'Terrain_Network_Type': np.random.choice(['TypeA', 'TypeB', 'TypeC'], n_rows),
    'Terrain_Operating_System': np.random.choice(['Windows', 'Linux', 'Unix'], n_rows),
    'Terrain_Enclave': np.random.choice(['EnclaveA', 'EnclaveB', 'EnclaveC'], n_rows)
})
missions_location_df.to_csv(os.path.join(DATA_DIR, 'Missions_by_Location_and_Tasked_System.csv'), index=False)
missions_location_df.head()

,CY,Mission_Title,Country,State,City,Base,Tasked_System,Network_Map,Attachments,Tasked_Sub_System,Misc_System_Info_Equipment,CPT_Equipment,Tools,Terrain_Category,Terrain_Network_Type,Terrain_Operating_System,Terrain_Enclave
0,2025,Mission_1,Germany,Texas,Munich,WPAFB,System Z,Map1,1,SubB,InfoB,EquipC,ToolC,CatA,TypeA,Linux,EnclaveC
1,2024,Mission_2,Germany,Tokyo,Dayton,Randolph,System Y,Map1,4,SubA,InfoA,EquipB,ToolB,CatA,TypeB,Unix,EnclaveC
2,2024,Mission_3,Germany,Bavaria,San Antonio,Randolph,System Z,Map2,4,SubB,InfoA,EquipA,ToolC,CatB,TypeB,Windows,EnclaveA
3,2025,Mission_4,UK,Bavaria,San Antonio,Yokota,System Y,Map3,4,SubC,InfoC,EquipC,ToolC,CatC,TypeB,Unix,EnclaveC
4,2024,Mission_5,USA,Tokyo,Shinjuku,Ramstein,System Y,Map2,1,SubC,InfoC,EquipC,ToolB,CatA,TypeC,Linux,EnclaveA

In [ ]:
# 8) Tactical_Lessons_Learned
n_rows = 10
tactical_lessons_columns = [
    'Mission_Title', 'Debrief_Focus_Point_Problem_Statement', 'Contributing_Factors', 'Root_Cause',
    'Instructional_Fix', 'LL_LP_LO', 'DOTMLPFP_PAIC2', 'Big_Rocks'
]
tactical_lessons_df = pd.DataFrame({
    'Mission_Title': mission_titles,
    'Debrief_Focus_Point_Problem_Statement': [random_text(80) for _ in range(n_rows)],
    'Contributing_Factors': [random_text(80) for _ in range(n_rows)],
    'Root_Cause': [random_text(80) for _ in range(n_rows)],
    'Instructional_Fix': [random_text(80) for _ in range(n_rows)],
    'LL_LP_LO': [random_text(80) for _ in range(n_rows)],
    'DOTMLPFP_PAIC2': [random_text(80) for _ in range(n_rows)],
    'Big_Rocks': [random_text(80) for _ in range(n_rows)]
})
tactical_lessons_df.to_csv(os.path.join(DATA_DIR, 'Tactical_Lessons_Learned.csv'), index=False)
tactical_lessons_df.head()

,Mission_Title,Debrief_Focus_Point_Problem_Statement,Contributing_Factors,Root_Cause,Instructional_Fix,LL_LP_LO,DOTMLPFP_PAIC2,Big_Rocks
0,Mission_1,cyber response operation cyber operation cyber...,network intel intel incident cyber incident as...,system assessment threat security assessment a...,security incident response intel security secu...,intel threat network threat incident threat cy...,incident network cyber threat operation intel ...,cyber threat network intel intel intel assessm...
1,Mission_2,assessment security intel operation intel netw...,threat system security security assessment res...,security response assessment system threat thr...,incident incident incident network cyber opera...,threat system threat intel security threat net...,assessment assessment security assessment inci...,security system response network incident resp...
2,Mission_3,operation network system threat assessment inc...,response response network security threat oper...,incident threat system network assessment resp...,cyber response intel network system incident n...,operation response assessment threat system in...,cyber system network system operation network ...,operation intel network response assessment th...
3,Mission_4,system incident threat response incident cyber...,response threat system response system inciden...,threat system cyber assessment system network ...,cyber incident network system cyber network in...,intel system assessment security threat operat...,security security operation cyber threat threa...,intel threat system security cyber system resp...
4,Mission_5,assessment incident threat response network se...,security assessment security network response ...,intel operation system incident intel threat o...,cyber operation network cyber response cyber s...,cyber system cyber response threat security in...,operation operation network system security se...,response intel incident network cyber security...

---

**All CSV files have been generated and saved in the `../data/` folder.**

You can adjust the number of rows or column values as needed for your use case.